### ISSUE TITLE
Requires Ctools

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/fel#1]
Form element layout fields in Drupal requires ctools.

**Comment by Graham-72** [comment]
Necessary ctools functions added to fel.module

**Comment by kelizoliva** [comment]
Not sure how this was closed. ctools is still listed as a requirement to enable Form element layout fields.

**Comment by Graham-72** [comment]
@kelizoliva yes indeed. Hopefully now put right by the PR for issue #3.
