### ISSUE TITLE
theme_fel_form_element() overwriting attributes

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/fel#11]
This came up because the Search field in the Layout "Add Block" modal form was not working, and the block list was missing its striping as well. I found that this function is creating a DIV with a set of attributes that it creates. Other code may have already defined attributes for that wrapper, however, in the '#wrapper_attributes' value of the form element.

Though I only needed the class in this specific case, it seems to me that a better approach would be to start with the values in '#wrapper_attributes', if any.

**Comment by bradbulger** [comment]
I made a pull request with a fix for this
https://github.com/backdrop-contrib/fel/pull/12

**Comment by Graham-72** [comment]
@bradbulger thanks for this.
