### ISSUE TITLE
Hyphens in project repository name instead of underscores + project name should match project filenames.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/fel#2]
The project repo name is `form-element-layout` but should be `form_element_layout` instead.

The files are `fel.info` and `fel.module`. You should either change these to be the same as the project repo name (once corrected to use underscores) or move the code to a new https://github.com/backdrop-contrib/fel repository and remove this one.

Is this project active anyways?

**Comment by Graham-72** [comment]
> Hyphens in project repository name instead of underscores

Having (for example) backdrop-contrib/form_element_layout rather than backdrop-contrib/form-element-layout seems a little bit inconsistent - just saying. I must remind myself of the rules on this.

> Is this project active anyways

I am sure there was a reason why I ported it and I must go back and check. But how would I know whether anyone else is using it?

**Comment by klonos** [comment]
> ...how would I know whether anyone else is using it?

Hmm... I hear @quicksketch saying in every weekly meeting that our number crunching script is not quite working yet. So I wouldn't know that.

Usually I file issues like this when I download a project and notice nits here and there, but this time it wasn't because I wanted to use the module myself. I simply noticed inconsistencies in the module name/path when I was testing either the forthcoming Project Browser or the project search on backdropcms.org.

**Comment by Graham-72** [comment]
I think I will keep it active and make any necessary changes. But it seems I do not have the permission in Github to change the repository name. :-1: 
![options 2016-05-02 08-59-40](https://cloud.githubusercontent.com/assets/10559274/14949781/902b9bda-1044-11e6-8892-fcf73e54f641.png)

**Comment by klonos** [comment]
The "Rename" button is activated only once you have made an edit in the "Repository name" field. Have you tried that or were you discouraged by the fact that the button is disabled? Let me know if you still cannot do it and I'll get it done for you.

**Comment by klonos** [comment]
...I wouldn't even care about the repo name if it wasn't the fact that the folder created within the release packages get hyphens too and IIANM, then the .info, .module etc. files need to also be changed to have hyphens (which is against our coding standards I think). Anyways, point is that there would be issues and new users would not know why. So lets fix it.

**Comment by klonos** [comment]
...never mind. We both seem to agree that this needs to happen, so I just went ahead and did the rename of the project to save you some energy and time and to avoid issues with people downloading this.

**Comment by klonos** [comment]
...would be nice though if you checked whether you actually have permissions to rename anyways (you should by definition).

**Comment by Graham-72** [comment]
> were you discouraged by the fact that the button is disabled

Yes I was, and you are quite right of course, the button came to life when I made a change. But I see you have done it. Thanks. 

I am developing a phobia of Github! :smile:

**Comment by klonos** [comment]
No worries. I also deleted the previous 1.0.0 release and created a new one that has a downloadable file with fel.zip as filename instead of form-element-layout.zip or form-element-layout.zip and I just checked and made sure that the folder included in it is indeed `fel`. All good :+1:

**Comment by klonos** [comment]
...though now it shows myself as the author of the release. Sorry about that. If you mind, then go ahead and delete and re-create a new release yourself.

**Comment by klonos** [comment]
...also, [a new release node was created on backdropcms.org](https://backdropcms.org/project/fel), but the old one [is not deleted](https://backdropcms.org/project/form-element-layout) (despite that I have set the node to unpublished), so [both come up as search results](https://backdropcms.org/modules?s=form+element+layout) :disappointed: 

@jenlampton @quicksketch ?? ...help please? Was that the right way to go about doing things? Should we be setting redirects from the old nodes? That's what GitHub does, because https://github.com/backdrop-contrib/form-element-layout still works and so does https://github.com/backdrop-contrib/form_element_layout (they both redirect to https://github.com/backdrop-contrib/fel)

**Comment by jenlampton** [comment]
@klonos I have deleted the old project, and added the name as a redirect to the new project. All good ideas 👍  Feel free to do the same yourself next time, and thank you for checking :)
